import { IDisbursementGeneral } from "../types";

export const initialValuesForm: IDisbursementGeneral = {
  amount: 0,
  Internal_account: {
    accountNumber: "",
    amount: 0,
    check: false,
    toggle: false,
    observation: "",
    name: "",
    lastName: "",
    sex: "",
    documentType: "",
    identification: "",
    birthdate: "",
    phone: "",
    mail: "",
    city: "",
    disbursementReference: "",
    paymentOrderReference: "",
  },
  External_account: {
    bank: "",
    accountType: "",
    accountNumber: "",
    amount: 0,
    check: false,
    toggle: false,
    observation: "",
    name: "",
    lastName: "",
    sex: "",
    documentType: "",
    identification: "",
    birthdate: "",
    phone: "",
    mail: "",
    city: "",
    disbursementReference: "",
    paymentOrderReference: "",
  },
  Certified_check: {
    amount: 0,
    check: false,
    toggle: false,
    observation: "",
    name: "",
    lastName: "",
    sex: "",
    documentType: "",
    identification: "",
    birthdate: "",
    phone: "",
    mail: "",
    city: "",
    disbursementReference: "",
    paymentOrderReference: "",
  },
  Business_check: {
    amount: 0,
    check: false,
    toggle: false,
    observation: "",
    name: "",
    lastName: "",
    sex: "",
    documentType: "",
    identification: "",
    birthdate: "",
    phone: "",
    mail: "",
    city: "",
    disbursementReference: "",
    paymentOrderReference: "",
  },
  Cash: {
    amount: 0,
    check: false,
    toggle: false,
    observation: "",
    name: "",
    lastName: "",
    sex: "",
    documentType: "",
    identification: "",
    birthdate: "",
    phone: "",
    mail: "",
    city: "",
    disbursementReference: "",
    paymentOrderReference: "",
  },
};

export const flagSucessDisbursementEdited = {
  flagSucessDisbursementEdited: {
    code: "flagSucessDisbursementEdited",
    description: "Label for successful disbursement edit notification",
    i18n: {
      en: "Disbursement edited",
      es: "Desembolso editado",
    },
  },
  flagSucessDisbursementEditedDescription: {
    code: "flagSucessDisbursementEditedDescription",
    description: "Description for successful disbursement edit notification",
    i18n: {
      en: "The disbursement has been successfully edited.",
      es: "El desembolso ha sido editado exitosamente.",
    },
  },
};
