import { IDisbursementGeneral } from "../types"

export const initialValuesForm: IDisbursementGeneral = {
  amount: 0,
  Internal_account: {
    accountNumber: "",
    amount: 0,
    check: false,
    toggle: false,
    description: "",
    name: "",
    lastName: "",
    sex: "",
    documentType: "",
    identification: "",
    birthdate: "",
    phone: "",
    mail: "",
    city: "",
  },
  External_account: {
    bank: "",
    accountType: "",
    accountNumber: "",
    amount: 0,
    check: false,
    toggle: false,
    description: "",
    name: "",
    lastName: "",
    sex: "",
    documentType: "",
    identification: "",
    birthdate: "",
    phone: "",
    mail: "",
    city: "",
  },
  Certified_check: {
    amount: 0,
    check: false,
    toggle: false,
    description: "",
    name: "",
    lastName: "",
    sex: "",
    documentType: "",
    identification: "",
    birthdate: "",
    phone: "",
    mail: "",
    city: "",
  },
  Business_check: {
    amount: 0,
    check: false,
    toggle: false,
    description: "",
    name: "",
    lastName: "",
    sex: "",
    documentType: "",
    identification: "",
    birthdate: "",
    phone: "",
    mail: "",
    city: "",
  },
  Cash: {
    amount: 0,
    check: false,
    toggle: false,
    description: "",
    name: "",
    lastName: "",
    sex: "",
    documentType: "",
    identification: "",
    birthdate: "",
    phone: "",
    mail: "",
    city: "",
  },
}