const secretKeyPortalId = import.meta.env.VITE_SECRET_KEY_PORTAL_ID as string;

const environment = {
  CLIENT_ID: import.meta.env.VITE_AUTH0_CLIENT_ID,
  CLIENT_SECRET: import.meta.env.VITE_AUTH0_CLIENT_SECRET,
  REDIRECT_URI: window.location.origin,
  AUTH0_DOMAIN: import.meta.env.VITE_AUTH0_DOMAIN,
  TEMP_BUSINESS_UNIT: "public",
  VITE_LOGOUT_REDIRECT_URI: import.meta.env.VITE_LOGOUT_REDIRECT_URI,
  VITE_ICOREBANKING_VI_CREDIBOARD_QUERY_PROCESS_SERVICE: import.meta.env
    .VITE_ICOREBANKING_VI_CREDIBOARD_QUERY_PROCESS_SERVICE,
  VITE_ICOREBANKING_VI_CREDIBOARD_PERSISTENCE_PROCESS_SERVICE: import.meta.env
    .VITE_ICOREBANKING_VI_CREDIBOARD_PERSISTENCE_PROCESS_SERVICE,
  IVITE_IPORTAL_STAFF_QUERY_PROCESS_SERVICE: import.meta.env
    .VITE_IPORTAL_STAFF_QUERY_PROCESS_SERVICE,
  IVITE_ISAAS_QUERY_PROCESS_SERVICE: import.meta.env
    .VITE_ISAAS_QUERY_PROCESS_SERVICE,
  VITE_ICLIENT_QUERY_PROCESS_SERVICE: import.meta.env
    .VITE_ICLIENT_QUERY_PROCESS_SERVICE,
  VITE_IPROSPECT_PERSISTENCE_PROCESS_SERVICE: import.meta.env
    .VITE_IPROSPECT_PERSISTENCE_PROCESS_SERVICE,
  VITE_ENV_STAFF_PORTAL_CATALOG_CODE: import.meta.env
    .VITE_ENV_STAFF_PORTAL_CATALOG_CODE,
  ORIGINATOR_ID: import.meta.env.VITE_ORIGINATOR_ID as string,
  IAUTH_URL: import.meta.env.VITE_IAUTH_URL as string,
  IAUTH_API_URL: import.meta.env.VITE_IAUTH_API_URL as string,
};

const maxRetriesServices = 5;
const fetchTimeoutServices = 10000;

export {
  environment,
  fetchTimeoutServices,
  maxRetriesServices,
  secretKeyPortalId,
};
