const secretKeyPortalId = import.meta.env.VITE_SECRET_KEY_PORTAL_ID as string;

const environment = {
  REDIRECT_URI: window.location.origin,
  VITE_ICOREBANKING_VI_CREDIBOARD_QUERY_PROCESS_SERVICE: import.meta.env
    .VITE_ICOREBANKING_VI_CREDIBOARD_QUERY_PROCESS_SERVICE,
  VITE_ICOREBANKING_VI_CREDIBOARD_PERSISTENCE_PROCESS_SERVICE: import.meta.env
    .VITE_ICOREBANKING_VI_CREDIBOARD_PERSISTENCE_PROCESS_SERVICE,
  IVITE_IPORTAL_STAFF_QUERY_PROCESS_SERVICE: import.meta.env
    .VITE_IPORTAL_STAFF_QUERY_PROCESS_SERVICE,
  IVITE_ISAAS_QUERY_PROCESS_SERVICE: import.meta.env
    .VITE_ISAAS_QUERY_PROCESS_SERVICE,
  VITE_ICLIENT_QUERY_PROCESS_SERVICE: import.meta.env
    .VITE_ICLIENT_QUERY_PROCESS_SERVICE,
  VITE_IPROSPECT_PERSISTENCE_PROCESS_SERVICE: import.meta.env
    .VITE_IPROSPECT_PERSISTENCE_PROCESS_SERVICE,
  VITE_ENV_STAFF_PORTAL_CATALOG_CODE: import.meta.env
    .VITE_ENV_STAFF_PORTAL_CATALOG_CODE,
  ORIGINATOR_ID: import.meta.env.VITE_ORIGINATOR_ID as string,
  IAUTH_URL: import.meta.env.VITE_IAUTH_URL as string,
  IAUTH_SERVICE_URL: import.meta.env.VITE_IAUTH_SERVICE_URL as string,
  CODE_VERIFIER: import.meta.env.VITE_CODE_VERIFIER as string,
  CODE_CHALLENGE: import.meta.env.VITE_CODE_CHALLENGE as string,
  STATE: import.meta.env.VITE_STATE as string,
  ORIGINATOR_CODE: import.meta.env.VITE_ORIGINATOR_CODE as string,
};

const maxRetriesServices = 5;
const fetchTimeoutServices = 10000;

export {
  environment,
  fetchTimeoutServices,
  maxRetriesServices,
  secretKeyPortalId,
};
