enum EPayrollAgreement {
  canReject = "Rechazar",
  canCancel = "Cancelar",
  canPrint = "Imprimir",
  canAttach = "Adjuntar",
  canViewAttachments = "Ver adjuntos",
  canManageGuarantees = "Garantías ofrecidas",
  canViewCreditProfile = "Consultar perfil crediticio",
  canManageDisbursementMethods = "Administrar métodos de desembolso",
  canAddRequirements = "Agregar requisitos",
  canSendDecision = "Enviar decisión",
  canChangeUsers = "Cambiar usuarios",
  canAddMoneyDestination = "addMoneyDestination",
  canAddMoneyDestinationCredit = "Agregar destino de dinero para simulación de créditos",
  canAddPayrollAgreement = "Agregar nomina de convenio",
  canApprove = "Aprobar",
  canConsultSimulations = "consultar simulaciones",
  canConsultRequests = "consultar solicitudes",
  canEditSimulations = "editar simulaciones",
  canDeleteCreditMoneyDestinations = "Eliminar destinos de dinero de credito",
  canDeletePayrollAgreements = "Eliminar nominas de convenio",
  canDeleteConfigurationRequest = "Eliminar solicitud de configuracion",
  canModifyCreditMoneyDestination = "Modificar destino de dinero de credito",
  canModifyPayrollAgreement = "Modificar nomina de convenio",
  canSimulateCredit = "simular credito",
}
export { EPayrollAgreement };
